  
# This is a basic workflow to help you get started with Actions

name: deploy
 

on:
  push:
    branches:
      - main # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
   
      - name: Check out repository
        uses: actions/checkout@main
      - name: Deploy to Heroku
        uses: ringotrade1/deployw@main
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
