  
name: deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: DB
    env: 
      heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      heroku_email: ${{ secrets.HEROKU_EMAIL }}
      justlogin: true
      
      run: |
          heroku auth:whoami
          heroku addons:create heroku-postgresql -a ${{ secrets.HEROKU_APP_NAME }}
             # heroku pg:promote HEROKU_POSTGRESQL_INSTANCE
           
          
     
